@startuml
class Score {
    point : float
    - Start() : void
    Update() : void
    + AddScore() : void
    + AddScore(num:int) : void
    + GetScore() : string
}
MonoBehaviour <|-- Score
Score --> "score" Text
@enduml
